name: DEFAULT_imb_RATIO_stage2_mislas_bxnet
print_freq: 40
workers: 2
log_dir: 'logs'
model_dir: 'ckps'

# dataset & model setting
dataset: 'cub'
data_path: './data/DEFAULT'
num_classes: 1
imb_factor: 1.0
backbone: 'resnet32_fe'
resume: 'saved/binary/cifar10_imb01_stage1_mixup_bxnet/sgd_step/0.01/epochs_200_bs128/ckps/model_best.pth.tar'
head_class_idx:
  - 0
  - 0
med_class_idx:
  - 0
  - 0
tail_class_idx:
  - 0
  - 0


# distributed training
deterministic: False
distributed: False
gpu: 0
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False



# Train
mode: 'stage2'
smooth_head: 0.1
smooth_tail: 0.0
shift_bn: False
lr_factor: 0.2
lr: 0.1
batch_size: 128
weight_decay: 2e-4
num_epochs: 10
momentum: 0.9
mixup: False
alpha: null





