name: imagenet_resnet50_stage1_binary
print_freq: 100
workers: 16
log_dir: 'logs'
model_dir: 'ckps'


# dataset & model setting
dataset: 'imagenet'
data_path: 'Path/to/Data/ImageNet/'
num_classes: 1000
imb_factor: null
backbone: 'resnet50_fe'
resume: ''
head_class_idx:
  - 0
  - 390
med_class_idx:
  - 390
  - 835
tail_class_idx:
  - 835
  - 1000


# distributed training
deterministic: False
distributed: False
gpu: null
world_size: -1
rank: -1
dist_url: 'tcp://224.66.41.62:23456'
dist_backend: 'nccl'
multiprocessing_distributed: False


# Train
mode: 'stage1'
lr: 0.01
batch_size: 256
weight_decay: 5e-4
num_epochs: 180
momentum: 0.9
cos: True
mixup: False
alpha: 0.0




